__soa_out = ""
__soa_out += """
# ==============================================================================
# This file is generated by VSI compiler
# ILANG version:"""
__soa_nodes[1].val = str(utils.ilang_version)
__soa_out += __soa_nodes[1].val
__soa_out += """
# Build Date:"""
__soa_nodes[3].val = str(utils.build_time)
__soa_out += __soa_nodes[3].val
__soa_out += """
# default directive file normally empty
# ==============================================================================
# config_compile -unsafe_math_optimizations
# config_compile -pipeline_loops 20
# config_interface -m_axi_addr64"""
updated_directives = []
for directive in str(b.DIRECTIVES).strip(',').split(','):
    updated_directives.append(utils.expand_env(directive))
for d in updated_directives:
    __soa_out += """
"""
    if d != "None":
        __soa_nodes[16].val = str(d)
        __soa_out += __soa_nodes[16].val
__soa_out += """
"""
if __soa_last_callback:__soa_last_callback(__soa_state(), {**globals(), **locals()})
