# ==============================================================================
# This file is generated by VSI compiler
# ILANG version:V2019.2_Release_1.0-149-g78d8f9a
# Build Date:2020-02-28T14:57:19
# default directive file normally empty
# ==============================================================================
# config_compile -unsafe_math_optimizations
# config_compile -pipeline_loops 20
# config_interface -m_axi_addr64

